\c hydaelyn yagi2

INSERT INTO item(name, can_take)
    VALUES
        ('清金鉱', true),
        ('クロマイト', true),
        ('アルマンディン', true),
        ('硬拳石', true),
        ('ロードナイト原石', true),
        ('ロードナイト', false),
        ('殺生石の欠片', false),
        ('輝水鉛鉱', true),
        ('蛇紋石', true),
        ('インペリアルジェード原石', true),
        ('インペリアルジェード', false),
        ('清金砂', true),
        ('翠銀鉱', true),
        ('ショール', true),
        ('アズライト原石', true),
        ('アズライト', false),
        ('真砂砂鉄', true),
        ('パーライト', true),
        ('黄土', true),
        ('軽銅鉱', true),
        ('餅鉄', true),
        ('スタースピネル原石', true),
        ('スタースピネル', false),
        ('翠銀砂', true),
        ('廃霊鉱', true),
        ('珪藻土', true),
        ('魔鉄鉱', true),
        ('カイヤナイト原石', true),
        ('カイヤナイト', false),
        ('粘板岩砥石', true),
        ('トリフェーン原石', true),
        ('トリフェーン', false),
        ('魔銅砂', true);
