\c hydaelyn yagi2

INSERT INTO item(name, can_take)
    VALUES
        ('悠久の霊砂', false),
        ('豊穣の霊砂', false),
        ('深淵の霊砂', false),
        ('ハロードバジル', true),
        ('極光の霊砂', false),
        ('ラールガースタッフ', true),
        ('アラミゴ塩', true),
        ('ニップルワート', true),
        ('パラースエンチャントインク', false),
        ('チックウィード', true),
        ('御形', true),
        ('アリッサム', true),
        ('ヤンサセリ', true),
        ('グロースフォーミュラ・テータ', false),
        ('柿渋', false),
        ('夜光の霊砂', false),
        ('風茶葉', true),
        ('パーシモンリーフ', true),
        ('ダリウムエンチャントインク', false),
        ('岩清水', true),
        ('カブトにかわ', false),
        ('松脂', true),
        ('剛力の霊水G1', false),
        ('眼力の霊水G1', false),
        ('活力の霊水G1', false),
        ('知力の霊水G1', false),
        ('心力の霊水G1', false),
        ('ホーリーバジル', true),
        ('グロースフォーミュラ・エータ', false),
        ('キュプロエンチャントインク', false),
        ('にがり', false),
        ('ギラバニア鉱泉水', true),
        ('粘板岩', true),
        ('鱗粉', false),
        ('ギラバニアアルメン', true);
