\c hydaelyn yagi2

INSERT INTO item(name, can_take)
    VALUES
        ('オサードプラム', true),
        ('ドマ茄子', true),
        ('ジャムメルの肉', false),
        ('ナノリソ', true),
        ('ジャムメルジンジャー', true),
        ('パーシモン', true),
        ('紅玉昆布', true),
        ('大根', true),
        ('ギラバニアカロット', true),
        ('蓮根', true),
        ('サンキャベツ', true),
        ('フェンネル', true),
        ('ステップミルク', false),
        ('ケナガウシの肩肉', false),
        ('葛根', true),
        ('タケノコ', true),
        ('メークインポポト', true),
        ('うるち米', false),
        ('馬芹', true),
        ('米酢', false),
        ('椎茸', true),
        ('シュガービート', true),
        ('グリーンリーキ', true),
        ('大豆', true),
        ('木綿豆腐', false),
        ('ビートシュガー', false),
        ('アマノリ', true),
        ('ワイルドポポト', true),
        ('料理酒', false),
        ('綿実油', false),
        ('ベニツノの笹身', false),
        ('マウンテンポポト', true),
        ('蕎麦の実', true),
        ('藻塩', false),
        ('玉藻', true),
        ('ガガナの卵', false),
        ('ロークワット', true),
        ('高原小麦', true),
        ('高原小麦粉', false),
        ('醤油', false),
        ('味噌', false);
